=== mawiegand/game_server/rules/rules.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT Rules (General, Languages?, ResourceTypes?, BuildingTypes?, ScienceTypes?, UnitCategories?, UnitTypes?)>
<!ELEMENT General (Game, Version, Languages)>
<!ELEMENT Game (#PCDATA)>
<!ATTLIST Game 
  branch CDATA #REQUIRED
  tag CDATA #IMPLIED
>
<!ELEMENT Version EMPTY>
<!ATTLIST Version 
  major CDATA #REQUIRED
  minor CDATA #REQUIRED
  build CDATA #REQUIRED
>

<!--Languages-->
<!ELEMENT Languages (Language*)>
<!ELEMENT Language (#PCDATA)>
<!ATTLIST Language locale ID #REQUIRED>

<!--Types-->
<!ELEMENT ResourceTypes (Resource*)>
<!ELEMENT SettlementTypes (Settlement*)>
<!ELEMENT BuildingTypes (Building*)>
<!ELEMENT BuildingCategories (BuildingCategory*)>
<!ELEMENT BuildingGroups (BuildingGroup*)>
<!ELEMENT ScienceTypes (Science*)>
<!ELEMENT UnitTypes (Unit*)>
<!ELEMENT UnitCategories (UnitCategory*)>

<!--Resource-->
<!ELEMENT Resource (Name+, RatingValue, TakeoverValue, StealRatio, DestroyRatio, SafeStorage, MaxStorage, Production)>
<!ATTLIST Resource id ID #REQUIRED hidden (0 | 1) "0">

<!--Settlements-->
<!ELEMENT Settlement (Name+, Description+, BuildingSlot*)>
<!ATTLIST Settlement 
  id ID #REQUIRED
	conquerable (true | false) "false"
	destroyable (true | false) "false"
>

<!ELEMENT BuildingSlot (BuildingOption+)>
<!ATTLIST BuildingSlot 
	number CDATA #REQUIRED
	max-level CDATA #REQUIRED 
>

<!ELEMENT BuildingOption EMPTY>
<!ATTLIST BuildingOption 
	category IDREF #REQUIRED 
>

<!--Buildings-->

<!ELEMENT BuildingCategory (Name+, Description+, Position?)>
<!ATTLIST BuildingCategory 
  id ID #REQUIRED 
>

<!ELEMENT BuildingGroup EMPTY>
<!ATTLIST BuildingGroup 
  id ID #REQUIRED 
>

<!ELEMENT Building (Name+, Description+, Position?, Cost*, ProductionTime, Requirement*, Limit?, Upkeep*, Production*, Abilities)>
<!ATTLIST Building 
  id ID #REQUIRED 
  category IDREF #REQUIRED
  group IDREF #REQUIRED
	buyable (false | true) "true"
	demolishable (false | true) "true"
	destructable (false | true) "true"
  hidden (0 | 1) "0"
>

<!--Science-->
<!ELEMENT Science (Name+, Description+, Position?, Cost*, ProductionTime, MaxDevelopmentLevel, (Requirement | EffectReq)*)>
<!ATTLIST Science id ID #REQUIRED hidden (0 | 1) "0">

<!--Units-->
<!ELEMENT UnitCategory (Name+, Description+, Position?, Ability*, TargetPriorities?)>
<!ATTLIST UnitCategory 
  id ID #REQUIRED 
>
<!ELEMENT Unit (Name+, Description+, Position?, Velocity, ActionPoints, Initiative, Attack, CriticalDamage, Armor, Overrunnable, Hitpoints, Effectiveness*, Encumbrance*)>
<!ATTLIST Unit 
  id ID #REQUIRED 
  category IDREF #REQUIRED
>

<!ELEMENT TargetPriorities (TargetList, TargetList)>
<!ATTLIST TargetPriorities
	testType CDATA #REQUIRED
	testCategory IDREF #IMPLIED
>

<!ELEMENT TargetList (Target)>
<!ELEMENT Target EMPTY>
<!ATTLIST Target
 id IDREF #REQUIRED
>


<!--Webinterface: Production-->
<!ELEMENT Cost (#PCDATA | object)*>
<!ATTLIST Cost id IDREF #REQUIRED>
<!ELEMENT object EMPTY>
<!ATTLIST object id IDREF #REQUIRED>

<!--Ability-->
<!ELEMENT Ability EMPTY>
<!ATTLIST Ability
 id CDATA #REQUIRED
>

<!--Requirement-->
<!ELEMENT Requirement EMPTY>
<!ATTLIST Requirement id IDREF #REQUIRED min CDATA "0" max CDATA #IMPLIED>
<!ELEMENT EffectReq EMPTY>
<!ATTLIST EffectReq id IDREF #REQUIRED min CDATA #IMPLIED max CDATA #IMPLIED>

<!--Encumbrance-->
<!ELEMENT Encumbrance EMPTY>
<!ATTLIST Encumbrance id IDREF #REQUIRED value CDATA #REQUIRED>

<!--Combat-->
<!ELEMENT Initiative (#PCDATA)>
<!ELEMENT Attack (#PCDATA)>
<!ELEMENT CriticalDamage (#PCDATA)>
<!ATTLIST CriticalDamage 
  chance CDATA #REQUIRED
>
<!ELEMENT Armor (#PCDATA)>
<!ELEMENT Hitpoints (#PCDATA)>
<!ELEMENT Overrunnable (#PCDATA)>
<!ELEMENT Effectiveness (#PCDATA)>
<!ATTLIST Effectiveness 
  category IDREF #REQUIRED
>

<!--Common Leafs-->
<!ELEMENT Description (p*)>
<!ATTLIST Description lang IDREF "en_US">
<!ELEMENT Name (#PCDATA)>
<!ATTLIST Name lang IDREF "en_US">
<!ELEMENT p (#PCDATA)>
<!ELEMENT Position (#PCDATA)>
<!ELEMENT Velocity (#PCDATA)>
<!ELEMENT ActionPoints (#PCDATA)>

<!--entities-->
<!ENTITY apst "&amp;#39;">
<!ENTITY auml "&amp;auml;">
<!ENTITY ouml "&amp;ouml;">
<!ENTITY uuml "&amp;uuml;">
<!ENTITY Auml "&amp;Auml;">
<!ENTITY Ouml "&amp;Ouml;">
<!ENTITY Uuml "&amp;Uuml;">
<!ENTITY szlig "&amp;szlig;">

=== mawiegand/game_server/rules/units/rules_units_clubbers_3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Rules SYSTEM "../rules.dtd">

<Unit id="clubbers_3" category="unitcategory_infantry">
  <Name>Drunken Clubber</Name>
  <Name lang="de_DE">Betrunkener Keulenkrieger</Name>
  
  <Description lang="de_DE">
    <p>Manche Keulenkrieger tauchen sogar mit ihrem Bierfaß auf dem Schlachtfeld auf. Nichts geht über einen guten Schluck vor, nach und während der Schlacht. Leicht wankend gibt der betrunkene Keulenkrieger auch ein schwierigeres Ziel für die Fernkämpfer ab. Nur leider zielen diese sowieso nicht, so dass sie weiterhin sehr tödlich für die Keulenkrieger sind.</p>		
  </Description>
  <Description lang="en_US">
    <p>Some clubbers even show up on the battlefield with a barrel of beer. There’s nothing like a good swig of beer before, during and after a battle. A slightly drunk clubber staggers and weaves, making him a much more difficult target for ranged combatants. But ranged combatants can’t aim anyway, which makes them just as deadly for clubbers. </p>
  </Description>
  <Flavour lang="en_US">
    <p>Very few clubbers survive their first battles, and almost none of them survive an entire war. Drinking enough beer increases their combat strength and reduces their ability to feel pain. </p>
  </Flavour>
  <Flavour lang="de_DE">
    <p>Sehr wenige Keulenkrieger überleben ihre ersten Schlachten, fast keiner überlebt einen Krieg. Durch ausreichend Bier erhöht sich die Kampfkraft und verringert sich das Schmerzempfinden.</p>
  </Flavour>
  <Cost id="resource_stone" round="true">70</Cost>  
  <Cost id="resource_wood" round="true">90</Cost>    
  <Cost id="resource_fur" round="true">120</Cost>    
  <ProductionTime shortenable="true">1000</ProductionTime>  
  <Velocity>1</Velocity>
  <ActionPoints>4</ActionPoints>
  <Initiative>16</Initiative>
  <Attack>6</Attack>
  <CriticalDamage chance="0.01">1</CriticalDamage>
  <Armor>7</Armor>
  <Overrunnable>true</Overrunnable>
  <Hitpoints>110</Hitpoints>
  <Effectiveness category="unitcategory_infantry">0.75</Effectiveness>
  <Effectiveness category="unitcategory_cavalry">1.5</Effectiveness>
  <Effectiveness category="unitcategory_artillery">1</Effectiveness>
  <Effectiveness category="unitcategory_siege">0.8</Effectiveness>    
  <Effectiveness category="unitcategory_special">1</Effectiveness>
  <RequirementGroup>
    <Requirement id="building_infantry_tower" min_level="15" />
    <Requirement id="building_fortress_fortification" min_level="14" />
  </RequirementGroup>
  <RequirementGroup>
    <Requirement id="building_barracks" min_level="15" />
  </RequirementGroup>
</Unit>

=== mawiegand/game_server/rules/rules_unitcategories.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Rules SYSTEM "rules.dtd">

  <UnitCategories>
    <UnitCategory id="unitcategory_infantry">
      <Name>Infantry</Name>
      <Name lang="de_DE">Fußtruppen</Name>
      <Description>
        <p>English description here.</p>
      </Description>
      <Description lang="de_DE">
        <p>Infanterie ist die Basiseinheit in jeder Truppe. Sie schützt Fernkämpfer vor direkt Angriffen und kann, wenn in ausreichender Zahl vorhanden, auch Flankenangriffe abwehren.</p>
      </Description>
      <Ability id="prevent-flanking" />
			<TargetPriorities testType="no_test">
				<TargetList>
					<Target id="infantry" />
					<Target id="cavalry" />
					<Target id="artillery" />
					<Target id="siege" />
				</TargetList>
			</TargetPriorities>
    </UnitCategory>
    <UnitCategory id="unitcategory_cavalry">
      <Name>cavalry</Name>
      <Name lang="de_DE">Reiter</Name>
      <Description>
        <p>English description here.</p>
      </Description>
      <Description lang="de_DE">
        <p>Berittene Einheiten bewegen sich schnell auf dem Schlachtfeld, und sind als einzige in der Lage, die gegnerischen Fußtruppen zu umgehen und feindliche Fernkämpfer direkt anzugreifen (Flankenangriff).</p>
      </Description>
      <Ability id="flanking" />
			<TargetPriorities testType="line_size_test" testCategory="infantry">
				<TargetList>
					<Target id="cavalry" />
					<Target id="artillery" />
					<Target id="infantry" />
					<Target id="siege" />
				</TargetList>
				<TargetList>
					<Target id="cavalry" />
					<Target id="infantry" />
					<Target id="artillery" />
					<Target id="siege" />
				</TargetList>
			</TargetPriorities>
    </UnitCategory>
    <UnitCategory id="unitcategory_artillery">
      <Name>Ranged Troops</Name>
      <Name lang="de_DE">Fernkämpfer</Name>
      <Description>
        <p>English description here.</p>
      </Description>
      <Description lang="de_DE">
        <p>Die Fernkämpfer schießen aus sicherer Distanz auf den Gegner, vorzugsweise auf Fußsoldaten. Im Nahkampf sind sie extrem anfällig.</p>
      </Description>
			<TargetPriorities testType="no_test">
				<TargetList>
					<Target id="infantry" />
					<Target id="artillery" />
					<Target id="cavalry" />
					<Target id="siege" />
				</TargetList>
			</TargetPriorities>
    </UnitCategory>
    <UnitCategory id="unitcategory_siege">
      <Name>Siege Weapons</Name>
      <Name lang="de_DE">Belagerungsgeräte</Name>
      <Description>
        <p>Siege Weapons support armies in battle against settlements.</p>
      </Description>
      <Description lang="de_DE">
        <p>Belagerungsgerät dient der Unterstützung im Kampf gegen Siedlungen.</p>
      </Description>
      <!--here we need a test: are there legal target buildings in the enemy faction? special abilities are on a per unit basis -->
			<TargetPriorities testType="no_test">
				<TargetList>
					<Target id="siege" />
					<Target id="artillery" />
					<Target id="infantry" />
					<Target id="cavalry" />
				</TargetList>
			</TargetPriorities>
    </UnitCategory>
  </UnitCategories>

=== mawiegand/game_server/rules/units/rules_units_light_cavalry_2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Rules SYSTEM "../rules.dtd">

    <Unit id="light_cavalry_2" category="unitcategory_cavalry">
      <Name>One-handed Ostrich Rider</Name>
      <Name lang="de_DE">Einhändiger Straußenreiter</Name>
      <Description lang="de_DE">
        <p>Eine handliche Keule in der freien Hand sind einhändige Straußenkrieger der Todfeind aller Fernkämpfer.</p>
        <p>Im Kampf gegen Keulenkrieger ziehen sie allerdings den Kürzeren, da sie nur eine kleine, nicht so schwere Keule bei sich führen.</p>
      </Description>
      <Description lang="en_US">
        <p>With a handy little club in his free hand, the one-handed ostrich rider is a deadly enemy for stone throwers. In battle against clubbers, though, they usually come off worse because they only have rather small, light clubs.</p>
      </Description>
      <Flavour lang="en_US">
        <p>Experienced ostrich riders only need one hand to hold on to their mounts, which means they have one hand free to do more practical things. Like picking their noses, for instance, or smashing in the skulls of their enemies.</p>
      </Flavour>
      <Flavour lang="de_DE">
        <p>Mit ausreichend Erfahrung braucht der Reiter nur noch eine Hand zum Festhalten und hat so die andere Hand für sinnvollere Tätigkeiten frei. Zum Beispiel um den Mädels zuzuwinken oder seinen Feinden den Schädel einzuhauen.</p>
      </Flavour>
      <Cost id="resource_stone" round="true">40</Cost>  
      <Cost id="resource_wood" round="true">35</Cost>    
      <Cost id="resource_fur" round="true">50</Cost>    
      <ProductionTime shortenable="true">800</ProductionTime>  
      <Velocity>1</Velocity>
      <ActionPoints>4</ActionPoints>
      <Initiative>26</Initiative>
      <Attack>7</Attack>
      <CriticalDamage chance="0.02">1</CriticalDamage>
      <Armor>5</Armor>
      <Overrunnable>true</Overrunnable>
      <Hitpoints>100</Hitpoints>
      <Effectiveness category="unitcategory_infantry">0.75</Effectiveness>
      <Effectiveness category="unitcategory_cavalry">1</Effectiveness>
      <Effectiveness category="unitcategory_artillery">1.5</Effectiveness>
      <Effectiveness category="unitcategory_siege">0.8</Effectiveness>   
      <Effectiveness category="unitcategory_special">1</Effectiveness>
      <RequirementGroup>
        <Requirement id="building_cavalry_tower" min_level="7" />
        <Requirement id="building_fortress_fortification" min_level="6" />  
      </RequirementGroup>
      <RequirementGroup>
        <Requirement id="building_stud" min_level="10" />  
      </RequirementGroup> 
    </Unit>

=== mawiegand/game_server/rules/units/rules_units_tree_huggers.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Rules SYSTEM "../rules.dtd">

 <Unit id="tree_huggers" category="unitcategory_infantry">
      <Name>Tree Huggers</Name>
      <Name lang="de_DE">Baum-Brutalo</Name>
  <Flavour lang="en_US">
    <p>Kills opposing units.</p>
  </Flavour>
  <Flavour lang="de_DE">
    <p>Wozu den Baum zu einer Keule verarbeiten, wenn man einfach den ganzen Baum schwingen kann.</p>
  </Flavour>
      <Description lang="de_DE">
        <p>Groß, stark, sauber rasierter Bart. Ein Baum-Brutalo legt sehr großen Wert auf sein Äußeres.</p> 
	<p>In der Schlacht bietet der Baum-Brutalo ein seltsames Schauspiel. Umhüllt von den rauschen Blättern seines Kampfbaumes wirbelt der Baum-Brutalo durch die gegnerischen Reihen wie ein Säberlzahntiger, der sich den Schwanz geklammt hat. Nicht den flauschigen, den anderen...</p>
	<p> Kein Feind kann einen Baum-Brutalo erreichen, wenn er erst einmal in Fahrt gekommen ist. Da bleibt nur wegrennen und hoffen, dass ihm irgendwann die Puste ausgeht, oder er von Steinen und Speeren gespickt zu Boden geht.</p>
      </Description>
      <Description lang="en_US">
        <p>What Tree-Huggers lack in brains, they make up for with sheer strength.</p>
		<p>Telling by an unverified legend, those guys are brought up in a tree-nursery.</p>
      </Description>
      <Cost id="resource_stone" round="true">140</Cost>  
      <Cost id="resource_wood" round="true">180</Cost>    
      <Cost id="resource_fur" round="true">240</Cost>    
      <ProductionTime shortenable="true">900</ProductionTime>  
      <Velocity>1</Velocity>
      <ActionPoints>4</ActionPoints>
      <Initiative>16</Initiative>
      <Attack>7</Attack>
      <CriticalDamage chance="0.02">2</CriticalDamage>
      <Armor>9</Armor>
      <Overrunnable>true</Overrunnable>
      <Hitpoints>135</Hitpoints>
      <Effectiveness category="unitcategory_infantry">0.75</Effectiveness>
      <Effectiveness category="unitcategory_cavalry">1.5</Effectiveness>
      <Effectiveness category="unitcategory_artillery">1</Effectiveness>
      <Effectiveness category="unitcategory_siege">0.8</Effectiveness> 
      <Effectiveness category="unitcategory_special">1</Effectiveness>   
      <RequirementGroup>
        <Requirement id="building_infantry_tower" min_level="15" />
        <Requirement id="building_fortress_main" min_level="15" />
      </RequirementGroup>
      <RequirementGroup>
        <Requirement id="building_barracks" min_level="20" />
        <Requirement id="building_copper_smelter" min_level="1" />
      </RequirementGroup>
    </Unit>

=== mawiegand/game_server/rules/units/rules_units_thrower_2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Rules SYSTEM "../rules.dtd">

    <Unit id="thrower_2" category="unitcategory_artillery">
      <Name>Pebble Thrower2</Name>
      <Name lang="de_DE"> Zielsicherer Kieselsteinwerfer</Name>
  <Flavour lang="en_US">
    <p>Kills opposing units.</p>
  </Flavour>
  <Flavour lang="de_DE">
    <p>Einen Stein auf fünfzig Meter Entfernung genau auf ein Ziel zu werfen, ist eine beeindruckende Leistung. Dummerweise stehen die Gegner meistens weiter weg.</p>
  </Flavour>
      <Description lang="de_DE">
        <p>Ein sicherer Wurf führt zu besseren Treffern. Nicht dass der Unterschied bemerkbar wäre, meist sind eh genug gegnerische Nahkämpfer da, aber es führt doch zu ein oder zwei kritischen Treffern.</p>
        <p>Ein bewegliches Ziel wie einen Straußenreiter zu treffen, ist eine große Leistung und der Unterschied zwischen Leben und Tod für einen Fernkämpfer.</p>
      </Description>
      <Description lang="en_US">
        <p>Small Stones, big Stones, a Peeble Thrower likes them all, as long as he can throw them at people. Ok, granted, the small ones are slightly prefered... Nevertheless, he may inflict moderate critical damage by sometimes hitting an opponent's eye.'</p>
      </Description>
      <Cost id="resource_stone" round="true">45</Cost>  
      <Cost id="resource_wood" round="true">45</Cost>
      <Cost id="resource_fur" round="true">60</Cost>    
      <ProductionTime shortenable="true">525</ProductionTime>  
      <Velocity>1</Velocity>
      <ActionPoints>4</ActionPoints>
      <Initiative>8</Initiative>
      <Attack>9</Attack>
      <CriticalDamage chance="0.05">6</CriticalDamage>
      <Armor>3</Armor>
      <Overrunnable>true</Overrunnable>
      <Hitpoints>50</Hitpoints>
      <Effectiveness category="unitcategory_infantry">1.5</Effectiveness>
      <Effectiveness category="unitcategory_cavalry">0.75</Effectiveness>
      <Effectiveness category="unitcategory_artillery">0.75</Effectiveness>
      <Effectiveness category="unitcategory_siege">0.8</Effectiveness>   
      <Effectiveness category="unitcategory_special">1</Effectiveness>   
      <RequirementGroup>
        <Requirement id="building_artillery_tower" min_level="5" />
        <Requirement id="building_fortress_main" min_level="5" />
      </RequirementGroup>
      <RequirementGroup>
        <Requirement id="building_firing_range" min_level="10" />
      </RequirementGroup>
    </Unit>

=== mawiegand/game_server/rules/units/rules_units_slingshot_warrior.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Rules SYSTEM "../rules.dtd">

    <Unit id="slingshot_warrior" category="unitcategory_artillery">
      <Name>Slingshot Warrior</Name>
      <Name lang="de_DE">Steinschleuderer</Name>
  <Flavour lang="en_US">
    <p>Kills opposing units.</p>
  </Flavour>
  <Flavour lang="de_DE">
    <p>Je hübscher die Schleuder, desto tödlicher auch der Steinschleuderer. Ursache hierfür ist weniger die Schleuder als die natürliche Selektion unter den Steinschleuderern. Wer hat die schönste Schleuder? Die Überlebenden!</p>
	</Flavour>
      <Description lang="de_DE">
    <p>Der Steinschleuderer trägt eine große Lederschleuder. Mit Hilfe dieser Schleuder schleudert der Steinschleuderer dem Gegner Steine entgegen.</p>
    <p>Ausschlaggebend für die Zielsicherheit ist dabei zum einen die Technik. Zwei bis drei Schwünge und dann am Scheitelpunkt mit einem Ruck den Stein schleudern. Zum anderen - und dies behaupten vor allem die Anfänger- ist die Art der Schleuder wichtig. Hochwertigere Ledersorten mit einer einwandfreien Verarbeitung und schönen Verzierungen treffen besser.</p>
	<p>Viele Tests konnten dies nicht belegen, dennoch sind die hochwertig verzierten Schleudern eine begehrte Beute. Sowohl beim Gegner als auch bei den eigenen Steinschleuderern.</p>
	  </Description>
      <Description lang="en_US">
        <p>Small Stones, big Stones, a Peeble Thrower likes them all, as long as he can throw them at people. Ok, granted, the small ones are slightly prefered... Nevertheless, he may inflict moderate critical damage by sometimes hitting an opponent's eye.'</p>
      </Description>
      <Cost id="resource_stone" round="true">135</Cost>  
	  <Cost id="resource_wood" round="true">90</Cost> 
      <Cost id="resource_fur" round="true">180</Cost>    
      <ProductionTime shortenable="true">1080</ProductionTime>
	  <Requirement id="building_firing_range" min_level="11" />	  
      <Velocity>1</Velocity>
      <ActionPoints>4</ActionPoints>
      <Initiative>8</Initiative>
      <Attack>19</Attack>
      <CriticalDamage chance="0.03">8</CriticalDamage>
      <Armor>13</Armor>
      <Overrunnable>true</Overrunnable>
      <Hitpoints>100</Hitpoints>
      <Effectiveness category="unitcategory_infantry">1.2</Effectiveness>
      <Effectiveness category="unitcategory_cavalry">0.92</Effectiveness>
      <Effectiveness category="unitcategory_artillery">1</Effectiveness>
      <Effectiveness category="unitcategory_siege">0.8</Effectiveness>
      <Effectiveness category="unitcategory_special">1</Effectiveness>                     
    </Unit>

=== mawiegand/game_server/rules/units/rules_units_neandertaler.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Rules SYSTEM "../rules.dtd">

<Unit id="neanderthal" category="unitcategory_infantry" trainable="false">
  <Name>Neanderthal</Name>
  <Name lang="de_DE">Neandertaler</Name>
  <Description lang="de_DE">
    <p>Wilder Vormenschenstamm.</p>		
  </Description>
  <Description lang="en_US">
    <p>Fierce Fighters.</p>
  </Description>
  <Flavour lang="en_US">
    <p>Don't talk, fight.</p>
  </Flavour>
  <Flavour lang="de_DE">
    <p>Reden nicht, handeln. Ã„h, schlagen.</p>
  </Flavour>
	<Requirement id="building_stud" min_level="100" />
  <Cost id="resource_stone" round="true">40</Cost>  
  <Cost id="resource_wood" round="true">20</Cost>    
  <Cost id="resource_fur" round="true">12</Cost>    
  <ProductionTime shortenable="true">1200</ProductionTime>  
  <Velocity>1</Velocity>
  <ActionPoints>4</ActionPoints>
  <Initiative>16</Initiative>
  <Attack>5</Attack>
  <CriticalDamage chance="0.01">1</CriticalDamage>
  <Armor>4</Armor>
  <Overrunnable>true</Overrunnable>
  <Hitpoints>90</Hitpoints>
  <Effectiveness category="unitcategory_infantry">0.75</Effectiveness>
  <Effectiveness category="unitcategory_cavalry">1.5</Effectiveness>
  <Effectiveness category="unitcategory_artillery">1</Effectiveness>
  <Effectiveness category="unitcategory_siege">0.8</Effectiveness>    
  <Effectiveness category="unitcategory_special">1</Effectiveness>
</Unit>

=== mawiegand/game_server/rules/rules_buildingcategories.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Rules SYSTEM "rules.dtd">

<BuildingCategories>
  <BuildingCategory id="building_category_fortress_main">
    <Name>Fortification</Name>
    <Name lang="de_DE">Festungsanlagen</Name>
    <Description lang="de_DE">
      <p>Allgemeine Verbesserungen, die in Festungen gebaut werden können.</p> 
    </Description>
    <Description lang="en_US">
      <p>Improvements to be build in fortresses.</p>
    </Description>
  </BuildingCategory>
  <BuildingCategory id="building_category_fortress_tower">
    <Name>Towers</Name>
    <Name lang="de_DE">Türme</Name>
    <Description lang="de_DE">
      <p>In Türmen untergebrachte militärische Verbesserungen von Festungen.</p> 
    </Description>
    <Description lang="en_US">
      <p>Towers that extend the military abilities of fortresses.</p>
    </Description>
  </BuildingCategory>
  <BuildingCategory id="building_category_fortress_special">
    <Name>Advanced Fortress Buildings</Name>
    <Name lang="de_DE">Spezielle Festungsgebäude</Name>
    <Description lang="de_DE">
      <p>Spezialgebäude von Festungen.</p> 
    </Description>
    <Description lang="en_US">
      <p>Towers that extend the military abilities of fortresses.</p>
    </Description>
  </BuildingCategory>
  <BuildingCategory id="building_category_wall">
    <Name>Defensive Barricade </Name>
    <Name lang="de_DE">Verteidigungswall</Name>
    <Description lang="de_DE">
      <p>Grundlegende Verteidigungseinrichtung einer jeden Siedlung.</p> 
    </Description>
    <Description lang="en_US">
      <p>Fundamental defensive building of any settlement.</p>
    </Description>
  </BuildingCategory>
  <BuildingCategory id="building_category_large_building">
    <Name>Large Buildings</Name>
    <Name lang="de_DE">Große Gebäude</Name>
    <Description lang="de_DE">
      <p>Wichtige Gebäude, die eine große Grundfläche benötigen.</p> 
    </Description>
    <Description lang="en_US">
      <p>Advanced buildings that must be built on a large building slot.</p>
    </Description>
  </BuildingCategory>
  <BuildingCategory id="building_category_small_building">
    <Name>Standard Buildings</Name>
    <Name lang="de_DE">Einfache Gebäude</Name>
    <Description lang="de_DE">
      <p>Grundlegende Gebäude, die überall, auf großen und kleinen Bauplätzen, gebaut werden können.</p> 
    </Description>
    <Description lang="en_US">
      <p>Fundamental buildings of any settlement that can be built on large as well as small building slots.</p>
    </Description>
  </BuildingCategory>
  <BuildingCategory id="building_category_special_building">
    <Name>Special Buildings</Name>
    <Name lang="de_DE">Spezialgebäude</Name>
    <Description lang="de_DE">
      <p>Spezielle Gebäude die nur auf kleinen Bauplätzen gebaut werden können.</p> 
    </Description>
    <Description lang="en_US">
      <p>Special buildings that can only be built on small building slots.</p>
    </Description>
  </BuildingCategory>
</BuildingCategories>
