=== mawiegand/game_server/rules/rules.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT Rules (General, Languages?, ResourceTypes?, BuildingTypes?, ScienceTypes?, UnitCategories?, UnitTypes?)>
<!ELEMENT General (Game, Version, Languages)>
<!ELEMENT Game (#PCDATA)>
<!ATTLIST Game 
  branch CDATA #REQUIRED
  tag CDATA #IMPLIED
>
<!ELEMENT Version EMPTY>
<!ATTLIST Version 
  major CDATA #REQUIRED
  minor CDATA #REQUIRED
  build CDATA #REQUIRED
>

<!--Languages-->
<!ELEMENT Languages (Language*)>
<!ELEMENT Language (#PCDATA)>
<!ATTLIST Language locale ID #REQUIRED>

<!--Types-->
<!ELEMENT ResourceTypes (Resource*)>
<!ELEMENT SettlementTypes (Settlement*)>
<!ELEMENT BuildingTypes (Building*)>
<!ELEMENT BuildingCategories (BuildingCategory*)>
<!ELEMENT BuildingGroups (BuildingGroup*)>
<!ELEMENT ScienceTypes (Science*)>
<!ELEMENT UnitTypes (Unit*)>
<!ELEMENT UnitCategories (UnitCategory*)>

<!--Resource-->
<!ELEMENT Resource (Name+, RatingValue, TakeoverValue, StealRatio, DestroyRatio, SafeStorage, MaxStorage, Production)>
<!ATTLIST Resource id ID #REQUIRED hidden (0 | 1) "0">

<!--Settlements-->
<!ELEMENT Settlement (Name+, Description+, BuildingSlot*)>
<!ATTLIST Settlement 
  id ID #REQUIRED
	conquerable (true | false) "false"
	destroyable (true | false) "false"
>

<!ELEMENT BuildingSlot (BuildingOption+)>
<!ATTLIST BuildingSlot 
	number CDATA #REQUIRED
	max-level CDATA #REQUIRED 
>

<!ELEMENT BuildingOption EMPTY>
<!ATTLIST BuildingOption 
	category IDREF #REQUIRED 
>

<!--Buildings-->

<!ELEMENT BuildingCategory (Name+, Description+, Position?)>
<!ATTLIST BuildingCategory 
  id ID #REQUIRED 
>

<!ELEMENT BuildingGroup EMPTY>
<!ATTLIST BuildingGroup 
  id ID #REQUIRED 
>

<!ELEMENT Building (Name+, Description+, Position?, Cost*, ProductionTime, Requirement*, Limit?, Upkeep*, Production*, Abilities)>
<!ATTLIST Building 
  id ID #REQUIRED 
  category IDREF #REQUIRED
  group IDREF #REQUIRED
	buyable (false | true) "true"
	demolishable (false | true) "true"
	destructable (false | true) "true"
  hidden (0 | 1) "0"
>

<!--Science-->
<!ELEMENT Science (Name+, Description+, Position?, Cost*, ProductionTime, MaxDevelopmentLevel, (Requirement | EffectReq)*)>
<!ATTLIST Science id ID #REQUIRED hidden (0 | 1) "0">

<!--Units-->
<!ELEMENT UnitCategory (Name+, Description+, Position?, Ability*, TargetPriorities?)>
<!ATTLIST UnitCategory 
  id ID #REQUIRED 
>
<!ELEMENT Unit (Name+, Description+, Position?, Velocity, ActionPoints, Initiative, Attack, CriticalDamage, Armor, Overrunnable, Hitpoints, Effectiveness*, Encumbrance*)>
<!ATTLIST Unit 
  id ID #REQUIRED 
  category IDREF #REQUIRED
>

<!ELEMENT TargetPriorities (TargetList, TargetList)>
<!ATTLIST TargetPriorities
	testType CDATA #REQUIRED
	testCategory IDREF #IMPLIED
>

<!ELEMENT TargetList (Target)>
<!ELEMENT Target EMPTY>
<!ATTLIST Target
 id IDREF #REQUIRED
>


<!--Webinterface: Production-->
<!ELEMENT Cost (#PCDATA | object)*>
<!ATTLIST Cost id IDREF #REQUIRED>
<!ELEMENT object EMPTY>
<!ATTLIST object id IDREF #REQUIRED>

<!--Ability-->
<!ELEMENT Ability EMPTY>
<!ATTLIST Ability
 id CDATA #REQUIRED
>

<!--Requirement-->
<!ELEMENT Requirement EMPTY>
<!ATTLIST Requirement id IDREF #REQUIRED min CDATA "0" max CDATA #IMPLIED>
<!ELEMENT EffectReq EMPTY>
<!ATTLIST EffectReq id IDREF #REQUIRED min CDATA #IMPLIED max CDATA #IMPLIED>

<!--Encumbrance-->
<!ELEMENT Encumbrance EMPTY>
<!ATTLIST Encumbrance id IDREF #REQUIRED value CDATA #REQUIRED>

<!--Combat-->
<!ELEMENT Initiative (#PCDATA)>
<!ELEMENT Attack (#PCDATA)>
<!ELEMENT CriticalDamage (#PCDATA)>
<!ATTLIST CriticalDamage 
  chance CDATA #REQUIRED
>
<!ELEMENT Armor (#PCDATA)>
<!ELEMENT Hitpoints (#PCDATA)>
<!ELEMENT Overrunnable (#PCDATA)>
<!ELEMENT Effectiveness (#PCDATA)>
<!ATTLIST Effectiveness 
  category IDREF #REQUIRED
>

<!--Common Leafs-->
<!ELEMENT Description (p*)>
<!ATTLIST Description lang IDREF "en_US">
<!ELEMENT Name (#PCDATA)>
<!ATTLIST Name lang IDREF "en_US">
<!ELEMENT p (#PCDATA)>
<!ELEMENT Position (#PCDATA)>
<!ELEMENT Velocity (#PCDATA)>
<!ELEMENT ActionPoints (#PCDATA)>

<!--entities-->
<!ENTITY apst "&amp;#39;">
<!ENTITY auml "&amp;auml;">
<!ENTITY ouml "&amp;ouml;">
<!ENTITY uuml "&amp;uuml;">
<!ENTITY Auml "&amp;Auml;">
<!ENTITY Ouml "&amp;Ouml;">
<!ENTITY Uuml "&amp;Uuml;">
<!ENTITY szlig "&amp;szlig;">

=== mawiegand/game_server/rules/units/rules_units_light_cavalry.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Rules SYSTEM "../rules.dtd">

    <Unit id="light_cavalry" category="unitcategory_cavalry">
      <Name>Ostrich Rider</Name>
      <Name lang="de_DE">Straußenreiter</Name>
      <Description lang="de_DE">
        <p>Der Straßenreiter ist die einfachste Berittene Einheit.</p> 
      </Description>
      <Description lang="en_US">
        <p>Ostritch riders are the simplest type of cavalry units.</p>
      </Description>
      <Flavour lang="en_US">
        <p>Ostritch riders are fast, that's it. This is why the riders have to focus all their concentration on controlling their mount.'</p>
      </Flavour>
      <Flavour lang="de_DE">
        <p>Straußenreiter sind schnell, sonst nichts. Deshalb müssen die Reiter ihre ganze Konzentration auf das Führen ihres Reittieres legen.</p>
      </Flavour>
      <Cost id="resource_stone" round="true">60</Cost>
      <Cost id="resource_wood" round="true">40</Cost>
      <Cost id="resource_fur" round="true">150</Cost>
      <ProductionTime shortenable="true">800</ProductionTime>
      <Velocity>1.2</Velocity>
      <ActionPoints>4</ActionPoints>
      <Initiative>26</Initiative>
      <Attack>6</Attack>
      <CriticalDamage chance="0.02">1</CriticalDamage>
      <Armor>5</Armor>
      <Overrunnable>true</Overrunnable>
      <Hitpoints>90</Hitpoints>
      <Effectiveness category="unitcategory_infantry">0.75</Effectiveness>
      <Effectiveness category="unitcategory_cavalry">1</Effectiveness>
      <Effectiveness category="unitcategory_artillery">1.5</Effectiveness>
      <Effectiveness category="unitcategory_siege">0.8</Effectiveness>   
      <Effectiveness category="unitcategory_special">1</Effectiveness>
      <RequirementGroup>
        <Requirement id="building_cavalry_tower" min_level="1" />
      </RequirementGroup>
      <RequirementGroup>
        <Requirement id="building_stud" min_level="1" />
      </RequirementGroup>
      <RequirementGroup>
          <Requirement id="building_stud_2" min_level="1" />
      </RequirementGroup>
    </Unit>

=== mawiegand/game_server/rules/units/rules_units_clubbers_2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Rules SYSTEM "../rules.dtd">

<Unit id="clubbers_2" category="unitcategory_infantry">
  <Name>Thick-skinned Clubber</Name>
  <Name lang="de_DE">Dickhäutiger Keulenkrieger</Name>
  
  <Description lang="de_DE">
    <p>Die dicke Haut schützt sie zwar vor Keulenschlägen, aber die spitzen Steine der Fernkämpfer hält sie nicht ab. Dafür tut es weniger weh, wenn man von einem Strauß überrannt wird und die Zeitspanne bis zur Bewusstlosigkeit muss nicht in Schmerzen durchstanden werden.</p>		
  </Description>
  <Description lang="en_US">
    <p>Their thick skin protects them against blows from others’ clubs, but doesn’t help much against the ranged combatants’ sharp stones. It makes being run over by an ostrich less painful, though – they’re not in so much agony until they pass out.</p>
  </Description>
  <Flavour lang="en_US">
    <p>You can tell battle-hardened clubbers by their thick skin and big clubs, and of course, the things they say. “You two? Ha! Go and fetch three more of you so you can give me a halfway fair fight!”</p>
  </Flavour>
  <Flavour lang="de_DE">
    <p>Erfahrene Keulenkrieger erkennt man an ihrer dicken Haut und ihrer großen Keule und natürlich an ihren Ausrufen. „Ihr zwei? Holt euch noch drei dazu, damit es ein halbwegs fairer Kampf wird!“</p>
  </Flavour>
  <Cost id="resource_stone" round="true">35</Cost>  
  <Cost id="resource_wood" round="true">45</Cost>    
  <Cost id="resource_fur" round="true">60</Cost>    
  <ProductionTime shortenable="true">800</ProductionTime>  
  <Velocity>1</Velocity>
  <ActionPoints>4</ActionPoints>
  <Initiative>16</Initiative>
  <Attack>6</Attack>
  <CriticalDamage chance="0.01">1</CriticalDamage>
  <Armor>6</Armor>
  <Overrunnable>true</Overrunnable>
  <Hitpoints>100</Hitpoints>
  <Effectiveness category="unitcategory_infantry">0.75</Effectiveness>
  <Effectiveness category="unitcategory_cavalry">1.5</Effectiveness>
  <Effectiveness category="unitcategory_artillery">1</Effectiveness>
  <Effectiveness category="unitcategory_siege">0.8</Effectiveness>    
  <Effectiveness category="unitcategory_special">1</Effectiveness>
  <RequirementGroup>
    <Requirement id="building_infantry_tower" min_level="7" />
    <Requirement id="building_fortress_fortification" min_level="6" />
  </RequirementGroup>
  <RequirementGroup>
    <Requirement id="building_barracks" min_level="10" />
  </RequirementGroup>
</Unit>

=== mawiegand/game_server/rules/units/rules_units_thrower_4.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Rules SYSTEM "../rules.dtd">

    <Unit id="thrower_4" category="unitcategory_artillery">
      <Name>Pebble Thrower4</Name>
      <Name lang="de_DE"> Speerschleuderer </Name>
      <Description lang="de_DE">
        <p>Ein Speer ist auch im Nahkampf, vor allem gegen Reiter, effektiv. Dumm nur, wenn man schon alle Speere weggeworfen hat, bevor ein Reiter angreift. Im Leitfaden für Speerwerfer steht, dass man immer einen Speer weniger werfen sollte, als man hat. Leider kann kein Speerwerfer zählen, geschweige denn lesen.</p> 
      </Description>
      <Description lang="en_US">
        <p>Small Stones, big Stones, a Peeble Thrower likes them all, as long as he can throw them at people. Ok, granted, the small ones are slightly prefered... Nevertheless, he may inflict moderate critical damage by sometimes hitting an opponent's eye.'</p>
      </Description>
      <Flavour lang="en_US">
        <p>Kills opposing units.</p>
      </Flavour>
      <Flavour lang="de_DE">
        <p>Wieso jemand einen Stock an einen Stein gebunden hat, ist unverständlich, denn Steine sind doch schon hervorragende Wurfgeschosse. Aber der Effekt ist großartig, größere Reichweite, zielgenauer und einfacher einzusammeln. Was will man mehr?</p>
      </Flavour>
      <Cost id="resource_stone" round="true">180</Cost>  
      <Cost id="resource_wood" round="true">180</Cost>
      <Cost id="resource_fur" round="true">280</Cost>    
      <ProductionTime shortenable="true">1300</ProductionTime>  
      <Velocity>1</Velocity>
      <ActionPoints>4</ActionPoints>
      <Initiative>8</Initiative>
      <Attack>12</Attack>
      <CriticalDamage chance="0.1">8</CriticalDamage>
      <Armor>3</Armor>
      <Overrunnable>true</Overrunnable>
      <Hitpoints>50</Hitpoints>
      <Effectiveness category="unitcategory_infantry">1.5</Effectiveness>
      <Effectiveness category="unitcategory_cavalry">0.75</Effectiveness>
      <Effectiveness category="unitcategory_artillery">0.75</Effectiveness>
      <Effectiveness category="unitcategory_siege">0.8</Effectiveness>  
      <Effectiveness category="unitcategory_special">1</Effectiveness>   
      <RequirementGroup>
        <Requirement id="building_firing_range" min_level="20" />
        <Requirement id="building_copper_smelter" min_level="1" />
      </RequirementGroup>
    </Unit>

=== mawiegand/game_server/rules/units/rules_units_clubbers.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Rules SYSTEM "../rules.dtd">

<Unit id="clubbers" category="unitcategory_infantry">
  <Name>Club Warrior</Name>
  <Name lang="de_DE">Keulenkrieger</Name>
  
  <Description lang="de_DE">
    <p>Die Keulenkrieger sind die ersten ernstzunehmenden Nahk√§mpfer.</p>		
  </Description>
  <Description lang="en_US">
    <p>Clubbers are the first type of melee unit to be reckoned with.</p>
  </Description>
  <Flavour lang="en_US">
    <p>Wields a club and is always at the front of the battle lines.</p>
  </Flavour>
  <Flavour lang="de_DE">
    <p>Eine Keule in der Hand und immer an vorderster Front.</p>
  </Flavour>
  <Cost id="resource_stone" round="true">20</Cost>
  <Cost id="resource_wood" round="true">30</Cost>    
  <Cost id="resource_fur" round="true">75</Cost>
  <ProductionTime shortenable="true">600</ProductionTime>
  <Velocity>1</Velocity>
  <ActionPoints>4</ActionPoints>
  <Initiative>16</Initiative>
  <Attack>6</Attack>
  <CriticalDamage chance="0.01">1</CriticalDamage>
  <Armor>5</Armor>
  <Overrunnable>true</Overrunnable>
  <Hitpoints>90</Hitpoints>
  <Effectiveness category="unitcategory_infantry">1</Effectiveness>
  <Effectiveness category="unitcategory_cavalry">1.5</Effectiveness>
  <Effectiveness category="unitcategory_artillery">0.75</Effectiveness>
  <Effectiveness category="unitcategory_siege">0.8</Effectiveness>    
  <Effectiveness category="unitcategory_special">1</Effectiveness>
  <RequirementGroup>
    <Requirement id="building_infantry_tower" min_level="1" />
  </RequirementGroup>
  <RequirementGroup>
    <Requirement id="building_barracks" min_level="5" />
  </RequirementGroup>
  <RequirementGroup>
      <Requirement id="building_barracks_2" min_level="1" />
  </RequirementGroup>
  
</Unit>

=== mawiegand/game_server/rules/units/rules_units_thrower.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Rules SYSTEM "../rules.dtd">

    <Unit id="thrower" category="unitcategory_artillery">
      <Name>Pebble Thrower</Name>
      <Name lang="de_DE">Kieselsteinwerfer</Name>
  <Flavour lang="en_US">
    <p>Kills opposing units.</p>
  </Flavour>
  <Flavour lang="de_DE">
    <p>Kämpft gegen andere Einheiten.</p>
  </Flavour>
      <Description lang="de_DE">
        <p>Große Steine, kleine Steine, ein Kieselsteinwerfer mag sie alle, solange er sie jemandem an den Kopf werfen kann. Ok, zugegeben, die kleinen mag er ein bisschen lieber. Nichtsdestotrotz kann er moderaten kritischen Schaden zufügen - denn, wie jeder weiß, das kann auch ins Auge gehen.</p> 
      </Description>
      <Description lang="en_US">
        <p>Small Stones, big Stones, a Peeble Thrower likes them all, as long as he can throw them at people. Ok, granted, the small ones are slightly prefered... Nevertheless, he may inflict moderate critical damage by sometimes hitting an opponent's eye.'</p>
      </Description>
      <Cost id="resource_stone" round="true">90</Cost>  
      <Cost id="resource_wood" round="true">45</Cost>
      <Cost id="resource_fur" round="true">67</Cost>    
      <ProductionTime shortenable="true">900</ProductionTime>  
      <Velocity>1</Velocity>
      <ActionPoints>4</ActionPoints>
      <Initiative>8</Initiative>
      <Attack>17</Attack>
      <CriticalDamage chance="0.02">5</CriticalDamage>
      <Armor>2</Armor>
      <Overrunnable>true</Overrunnable>
      <Hitpoints>60</Hitpoints>
      <Effectiveness category="unitcategory_infantry">1.2</Effectiveness>
      <Effectiveness category="unitcategory_cavalry">0.92</Effectiveness>
      <Effectiveness category="unitcategory_artillery">1</Effectiveness>
      <Effectiveness category="unitcategory_siege">0.8</Effectiveness>   
      <Effectiveness category="unitcategory_special">1</Effectiveness>                  
    </Unit>

=== mawiegand/game_server/rules/rules_buildings.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Rules SYSTEM "rules.dtd">

	<BuildingCategories>
	  <BuildingCategory id="building_category_fortress_main">
      <Name>Fortification</Name>
      <Name lang="de_DE">Festungsanlagen</Name>
      <Description lang="de_DE">
        <p>Allgemeine Verbesserungen, die in Festungen gebaut werden können.</p> 
      </Description>
      <Description lang="en_US">
        <p>Improvements to be build in fortresses.</p>
      </Description>
	  </BuildingCategory>
	  <BuildingCategory id="building_category_fortress_tower">
      <Name>Towers</Name>
      <Name lang="de_DE">Türme</Name>
      <Description lang="de_DE">
        <p>In Türmen untergebrachte militärische Verbesserungen von Festungen.</p> 
      </Description>
      <Description lang="en_US">
        <p>Towers that extend the military abilities of fortresses.</p>
      </Description>
	  </BuildingCategory>
  </BuildingCategories>

=== mawiegand/game_server/rules/units/rules_units_little_chief.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Rules SYSTEM "../rules.dtd">

<Unit id="little_chief" category="unitcategory_special">
  <Name>Little Chief</Name>
  <Name lang="de_DE">Kleiner Häuptling</Name>
  
  <Description lang="de_DE">
    <p>Ein Kleiner Häuptling ist ungefähr so beliebt wie die Begegnung mit einem hungrigen Dinosaurier. Als integranter, karrieresüchtiger, aalglatter Möchtegern ist der Kleine Häuptling das Rollenvorbild für ganze Generationen an Wichtigtuern. Zum Glück kann der Kleine Häuptling unter dem Vorwand der Gründung einer Lagerstätte aus der Siedlung verbannt werden.</p>
  </Description>
  <Description lang="en_US">
    <p>Little Chiefs are in charge of expansions.</p>
  </Description>
  <Flavour lang="en_US">
    <p>Kills opposing units.</p>
  </Flavour>
  <Flavour lang="de_DE">
    <p>Ein Kleiner Häuptling darf im Namen des richtigen Häuptlings eine Lagerstätte gründen. Tatsächlich ist das nur die einfachste Möglichkeit ihn aus der Siedlung zu bekommen. Eine Neugründung wäre ein Bonus.</p>
  </Flavour>
  <Cost id="resource_stone" round="true">3000</Cost>  
  <Cost id="resource_wood" round="true">3000</Cost>    
  <Cost id="resource_fur" round="true">1500</Cost>    
  <ProductionTime shortenable="true">7200</ProductionTime>
  <Velocity>1</Velocity>
  <ActionPoints>4</ActionPoints>
  <Initiative>10</Initiative>
  <Attack>1</Attack>
  <CriticalDamage chance="0.01">0</CriticalDamage>
  <Armor>1</Armor>
  <Overrunnable>true</Overrunnable>
  <Hitpoints>100</Hitpoints>
  <Effectiveness category="unitcategory_infantry">0.1</Effectiveness>
  <Effectiveness category="unitcategory_cavalry">0.1</Effectiveness>
  <Effectiveness category="unitcategory_artillery">0.1</Effectiveness>
  <Effectiveness category="unitcategory_siege">0.1</Effectiveness>
  <Effectiveness category="unitcategory_special">1</Effectiveness>
  <Requirement id="building_campfire" min_level="10" />  
  <!-- add ability to found settlement here not in category -->    
  <CanCreate id="settlement_outpost" />
</Unit>

=== mawiegand/game_server/rules/rules_settlements.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Rules SYSTEM "rules.dtd">

<SettlementTypes>
  <Settlement id="settlement_none" conquerable="false" destroyable="false">
    <Name lang="de_DE">Unbesiedelt</Name>
    <Name lang="en_US">Wilderness</Name>
    <Description lang="de_DE">Unbesiedeltes Gebiet. Spieler können hier siedeln.</Description>
    <Description lang="en_US">Unclaimed location. Players can settle here.</Description>
  </Settlement>
  <Settlement id="settlement_fortress" conquerable="true" destroyable="false">
    <Name lang="de_DE">Festung</Name>
    <Name lang="en_US">Fortress</Name>
    <Description lang="de_DE">Beherrscht eine Region mit allen Einwohnern, erlaubt es Steuern zu erheben und den Gebietszugang zu reglementieren.</Description>
    <Description lang="en_US">English Description.</Description>
    <BuildingSlot number="0" max-level="10">
      <BuildingOption building="building_category_fortress_main" />
    </BuildingSlot>
    <BuildingSlot number="1" max-level="10">
      <BuildingOption category="building_category_fortress_tower" />
    </BuildingSlot>
    <BuildingSlot number="2" max-level="10">
      <BuildingOption category="building_category_fortress_tower" />
    </BuildingSlot>
  </Settlement>
  <Settlement id="settlement_home_base" conquerable="false" destroyable="false">
    <Name lang="de_DE">Heimatstadt</Name>
    <Name lang="en_US">Home Town</Name>
    <Description lang="de_DE">Die Hauptsiedlung eines Stammes.</Description>
    <Description lang="en_US">English Description.</Description>
    <BuildingSlot number="0" max-level="20">
      <BuildingOption category="building_category_large_buildings" />
      <BuildingOption category="building_category_small_buildings" />
    </BuildingSlot>
    <BuildingSlot number="1" max-level="20">
      <BuildingOption category="building_category_large_buildings" />
      <BuildingOption category="building_category_small_buildings" />
    </BuildingSlot>
    <BuildingSlot number="2" max-level="20">
      <BuildingOption category="building_category_large_buildings" />
      <BuildingOption category="building_category_small_buildings" />
    </BuildingSlot>
    <BuildingSlot number="3" max-level="20">
      <BuildingOption category="building_category_large_buildings" />
      <BuildingOption category="building_category_small_buildings" />
    </BuildingSlot>    
    <BuildingSlot number="4" max-level="10">
      <BuildingOption category="building_category_small_buildings" />
    </BuildingSlot>
    <BuildingSlot number="5" max-level="10">
      <BuildingOption category="building_category_small_buildings" />
    </BuildingSlot>
    <BuildingSlot number="6" max-level="10">
      <BuildingOption category="building_category_small_buildings" />
    </BuildingSlot>
    <BuildingSlot number="7" max-level="10">
      <BuildingOption category="building_category_small_buildings" />
    </BuildingSlot>
    <BuildingSlot number="8" max-level="10">
      <BuildingOption category="building_category_small_buildings" />
    </BuildingSlot>
    <BuildingSlot number="9" max-level="10">
      <BuildingOption category="building_category_small_buildings" />
    </BuildingSlot>
    <BuildingSlot number="10" max-level="10">
      <BuildingOption category="building_category_wall" />
    </BuildingSlot>
    <BuildingSlot number="11" max-level="10">
      <BuildingOption category="building_category_fortification" />
    </BuildingSlot>
    <BuildingSlot number="12" max-level="10">
      <BuildingOption category="building_category_fortification" />
    </BuildingSlot>
  </Settlement>
  <Settlement id="settlement_outpost" conquerable="true" destroyable="true">
    <Name lang="de_DE">Außenposten</Name>
    <Name lang="en_US">Outpost</Name>
    <Description lang="de_DE">Außenlager eines Stammes.</Description>
    <Description lang="en_US">English Description.</Description>
    <BuildingSlot number="0" max-level="20">
      <BuildingOption category="building_category_large_buildings" />
      <BuildingOption category="building_category_small_buildings" />
    </BuildingSlot>
    <BuildingSlot number="1" max-level="20">
      <BuildingOption category="building_category_large_buildings" />
      <BuildingOption category="building_category_small_buildings" />
    </BuildingSlot>
    <BuildingSlot number="2" max-level="10">
      <BuildingOption category="building_category_small_buildings" />
    </BuildingSlot>
    <BuildingSlot number="3" max-level="10">
      <BuildingOption category="building_category_small_buildings" />
    </BuildingSlot>
    <BuildingSlot number="4" max-level="10">
      <BuildingOption category="building_category_small_buildings" />
    </BuildingSlot>
  </Settlement>
</SettlementTypes>
