=== mawiegand/game_server/rules/rules.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT Rules (General, Languages?, ResourceTypes?, BuildingTypes?, ScienceTypes?, UnitCategories?, UnitTypes?)>
<!ELEMENT General (Game, Version, Languages)>
<!ELEMENT Game (#PCDATA)>
<!ATTLIST Game 
  branch CDATA #REQUIRED
  tag CDATA #IMPLIED
>
<!ELEMENT Version EMPTY>
<!ATTLIST Version 
  major CDATA #REQUIRED
  minor CDATA #REQUIRED
  build CDATA #REQUIRED
>

<!--Languages-->
<!ELEMENT Languages (Language*)>
<!ELEMENT Language (#PCDATA)>
<!ATTLIST Language locale ID #REQUIRED>

<!--Types-->
<!ELEMENT ResourceTypes (Resource*)>
<!ELEMENT SettlementTypes (Settlement*)>
<!ELEMENT BuildingTypes (Building*)>
<!ELEMENT BuildingCategories (BuildingCategory*)>
<!ELEMENT BuildingGroups (BuildingGroup*)>
<!ELEMENT ScienceTypes (Science*)>
<!ELEMENT UnitTypes (Unit*)>
<!ELEMENT UnitCategories (UnitCategory*)>

<!--Resource-->
<!ELEMENT Resource (Name+, RatingValue, TakeoverValue, StealRatio, DestroyRatio, SafeStorage, MaxStorage, Production)>
<!ATTLIST Resource id ID #REQUIRED hidden (0 | 1) "0">

<!--Settlements-->
<!ELEMENT Settlement (Name+, Description+, BuildingSlot*)>
<!ATTLIST Settlement 
  id ID #REQUIRED
	conquerable (true | false) "false"
	destroyable (true | false) "false"
>

<!ELEMENT BuildingSlot (BuildingOption+)>
<!ATTLIST BuildingSlot 
	number CDATA #REQUIRED
	max-level CDATA #REQUIRED 
>

<!ELEMENT BuildingOption EMPTY>
<!ATTLIST BuildingOption 
	category IDREF #REQUIRED 
>

<!--Buildings-->

<!ELEMENT BuildingCategory (Name+, Description+, Position?)>
<!ATTLIST BuildingCategory 
  id ID #REQUIRED 
>

<!ELEMENT BuildingGroup EMPTY>
<!ATTLIST BuildingGroup 
  id ID #REQUIRED 
>

<!ELEMENT Building (Name+, Description+, Position?, Cost*, ProductionTime, Requirement*, Limit?, Upkeep*, Production*, Abilities)>
<!ATTLIST Building 
  id ID #REQUIRED 
  category IDREF #REQUIRED
  group IDREF #REQUIRED
	buyable (false | true) "true"
	demolishable (false | true) "true"
	destructable (false | true) "true"
  hidden (0 | 1) "0"
>

<!--Science-->
<!ELEMENT Science (Name+, Description+, Position?, Cost*, ProductionTime, MaxDevelopmentLevel, (Requirement | EffectReq)*)>
<!ATTLIST Science id ID #REQUIRED hidden (0 | 1) "0">

<!--Units-->
<!ELEMENT UnitCategory (Name+, Description+, Position?, Ability*, TargetPriorities?)>
<!ATTLIST UnitCategory 
  id ID #REQUIRED 
>
<!ELEMENT Unit (Name+, Description+, Position?, Velocity, ActionPoints, Initiative, Attack, CriticalDamage, Armor, Overrunnable, Hitpoints, Effectiveness*, Encumbrance*)>
<!ATTLIST Unit 
  id ID #REQUIRED 
  category IDREF #REQUIRED
>

<!ELEMENT TargetPriorities (TargetList, TargetList)>
<!ATTLIST TargetPriorities
	testType CDATA #REQUIRED
	testCategory IDREF #IMPLIED
>

<!ELEMENT TargetList (Target)>
<!ELEMENT Target EMPTY>
<!ATTLIST Target
 id IDREF #REQUIRED
>


<!--Webinterface: Production-->
<!ELEMENT Cost (#PCDATA | object)*>
<!ATTLIST Cost id IDREF #REQUIRED>
<!ELEMENT object EMPTY>
<!ATTLIST object id IDREF #REQUIRED>

<!--Ability-->
<!ELEMENT Ability EMPTY>
<!ATTLIST Ability
 id CDATA #REQUIRED
>

<!--Requirement-->
<!ELEMENT Requirement EMPTY>
<!ATTLIST Requirement id IDREF #REQUIRED min CDATA "0" max CDATA #IMPLIED>
<!ELEMENT EffectReq EMPTY>
<!ATTLIST EffectReq id IDREF #REQUIRED min CDATA #IMPLIED max CDATA #IMPLIED>

<!--Encumbrance-->
<!ELEMENT Encumbrance EMPTY>
<!ATTLIST Encumbrance id IDREF #REQUIRED value CDATA #REQUIRED>

<!--Combat-->
<!ELEMENT Initiative (#PCDATA)>
<!ELEMENT Attack (#PCDATA)>
<!ELEMENT CriticalDamage (#PCDATA)>
<!ATTLIST CriticalDamage 
  chance CDATA #REQUIRED
>
<!ELEMENT Armor (#PCDATA)>
<!ELEMENT Hitpoints (#PCDATA)>
<!ELEMENT Overrunnable (#PCDATA)>
<!ELEMENT Effectiveness (#PCDATA)>
<!ATTLIST Effectiveness 
  category IDREF #REQUIRED
>

<!--Common Leafs-->
<!ELEMENT Description (p*)>
<!ATTLIST Description lang IDREF "en_US">
<!ELEMENT Name (#PCDATA)>
<!ATTLIST Name lang IDREF "en_US">
<!ELEMENT p (#PCDATA)>
<!ELEMENT Position (#PCDATA)>
<!ELEMENT Velocity (#PCDATA)>
<!ELEMENT ActionPoints (#PCDATA)>

<!--entities-->
<!ENTITY apst "&amp;#39;">
<!ENTITY auml "&amp;auml;">
<!ENTITY ouml "&amp;ouml;">
<!ENTITY uuml "&amp;uuml;">
<!ENTITY Auml "&amp;Auml;">
<!ENTITY Ouml "&amp;Ouml;">
<!ENTITY Uuml "&amp;Uuml;">
<!ENTITY szlig "&amp;szlig;">

=== mawiegand/game_server/rules/buildings/rules_building_artillery_tower.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Rules SYSTEM "../rules.dtd">


<Building id="building_artillery_tower" group="military" category="building_category_fortress_tower" buyable="true" destructable="true">  
  <Name lang="de_DE">Ballistisches Erprobungszentrum</Name>
  <Name lang="en_US">Ballistic R+D</Name>
  <Description lang="de_DE">
    <p>Schulungszentrum für alle Distanzkämpfer.</p>
  </Description>
  <Description lang="en_US">
    <p>Trains artillery.</p>
  </Description>
  <Requirement id="science_ballistics" min_level="1" />
  <Requirement id="building_fortress_fortification" min_level="1" />  
  <Cost id="resource_stone" round="true">LEVEL*100</Cost>  
  <Cost id="resource_wood" round="true">LEVEL*10</Cost>    
  <ProductionTime shortenable="true">2*(LEVEL+1)+10</ProductionTime>             
</Building>

=== mawiegand/game_server/rules/units/rules_units_light_cavalry_4.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Rules SYSTEM "../rules.dtd">

    <Unit id="light_cavalry_4" category="unitcategory_cavalry">
      <Name>Ostrich Riders4</Name>
      <Name lang="de_DE">Dinoreiter</Name>
  <Flavour lang="en_US">
    <p>Kills opposing units.</p>
  </Flavour>
  <Flavour lang="de_DE">
    <p>Der Traum eines jeden neuen Reiters. Einen Dino reiten. Wenn man es endlich geschafft hat wünscht man sich doch lieber Fernkämpfer geworden zu sein. Ein Dino stinkt! Und die Dinowäsche nach einer Schlacht kann auch mal Tage dauern.</p>
  </Flavour>
      <Description lang="de_DE">
        <p>Als Reiter eines Dinos hat man genau zwei Aufgaben. Erstens nicht abgeworfen zu werden und zweitens den Dino immer wieder auf das Schlachtfeld zurückzulenken, wenn er erstmal durch die Schlachtreihen durchgeborchen ist. Mit Füßen, Schwanz und Zähnen werden die hilflosen Gegner niedergemäht.</p> 
        <p>Kein Wunder, gibt es zu Hause doch nichts zu fressen.</p> 
      </Description>
      <Description lang="en_US">
        <p>Ostrichs are not only delicious but also excellent and fast animals to be used in combats. Ostrich riders are very quick, but only lightly armored.</p>
      </Description>
      <Cost id="resource_stone" round="true">160</Cost>  
      <Cost id="resource_wood" round="true">140</Cost>    
      <Cost id="resource_fur" round="true">200</Cost>    
      <ProductionTime shortenable="true">950</ProductionTime>  
      <Velocity>1</Velocity>
      <ActionPoints>4</ActionPoints>
      <Initiative>26</Initiative>
      <Attack>10</Attack>
      <CriticalDamage chance="0.02">1</CriticalDamage>
      <Armor>6</Armor>
      <Overrunnable>true</Overrunnable>
      <Hitpoints>125</Hitpoints>
      <Effectiveness category="unitcategory_infantry">0.75</Effectiveness>
      <Effectiveness category="unitcategory_cavalry">1</Effectiveness>
      <Effectiveness category="unitcategory_artillery">1.5</Effectiveness>
      <Effectiveness category="unitcategory_siege">0.8</Effectiveness>   
      <Effectiveness category="unitcategory_special">1</Effectiveness>
      <RequirementGroup>
        <Requirement id="building_cavalry_tower" min_level="15" />
        <Requirement id="building_fortress_main" min_level="15" />
      </RequirementGroup>
      <RequirementGroup>
        <Requirement id="building_stud" min_level="20" />
        <Requirement id="building_copper_smelter" min_level="1" />
      </RequirementGroup>
    </Unit>

=== mawiegand/game_server/rules/units/rules_units_warrior.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Rules SYSTEM "../rules.dtd">

<Unit id="warrior" category="unitcategory_infantry">
  <Name>Warrior</Name>
  <Name lang="de_DE">Krieger</Name>
  <Description lang="de_DE">
    <p>Der Krieger ist eine schwache Nahkampfeinheit zur Verteidigung einer jungen Heimatsiedlung.</p>
  </Description>
  <Description lang="en_US">
    <p>The strongest, toughest and most stupid men of your tribe are trained as warriors. Having no effective weapons at their disposal, unarmed warriors overwhelm their opponents by pure muscle power and their strong will - or at least they try for a while. They can be trained as long as there are no armed melee units available in the same settlement. Very weak against all unit types apart from melee fighters.</p>
    <p>Can only be trained as long as there are no armed melee units available in the same settlement. Very weak against any other unit type but melee units.</p>
  </Description>
  <Flavour lang="en_US">
    <p>An affordable, unarmed warrior used for hunting down neanderthals and other players' weakest units.</p>
  </Flavour>
  <Flavour lang="de_DE">
    <p>GÃ¼nstiger unbewaffneter Krieger zur Abwehr von Neandertalern und schwachen Gegnern.</p>
  </Flavour>
  <Cost id="resource_stone" round="true">5</Cost>
  <Cost id="resource_wood" round="true">5</Cost>    
  <Cost id="resource_fur" round="true">50</Cost>
  <ProductionTime shortenable="true">800</ProductionTime>
  <Velocity>1</Velocity>
  <ActionPoints>4</ActionPoints>
  <Initiative>16</Initiative>
  <Attack>5</Attack>
  <CriticalDamage chance="0.01">1</CriticalDamage>
  <Armor>4</Armor>
  <Overrunnable>true</Overrunnable>
  <Hitpoints>90</Hitpoints>
  <Effectiveness category="unitcategory_infantry">1</Effectiveness>
  <Effectiveness category="unitcategory_cavalry">0.5</Effectiveness>
  <Effectiveness category="unitcategory_artillery">0.5</Effectiveness>
  <Effectiveness category="unitcategory_siege">0.5</Effectiveness>    
  <Effectiveness category="unitcategory_special">0.5</Effectiveness>
  <RequirementGroup>
    <Requirement id="building_infantry_tower" max_level="0" />
    <Requirement id="building_barracks" min_level="1" max_level="4" />
  </RequirementGroup>
  
</Unit>

=== mawiegand/game_server/rules/rules.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Rules SYSTEM "rules.dtd">
<Rules>
  <General>
    <Languages>
      <Language locale="en_US">English (US)</Language>
      <Language locale="de_DE">Deutsch</Language>
    </Languages>
  </General>
  <UnitCategories>
    <UnitCategory id="infantry">
      <Name>Infantry</Name>
      <Name lang="de_DE">Fußtruppen</Name>
      <Description>
        <p>English description here.</p>
      </Description>
      <Description lang="de_DE">
        <p>Infanterie ist die Basiseinheit in jeder Truppe. Sie schützt Fernkämpfer vor direkt Angriffen und kann, wenn in ausreichender Zahl vorhanden, auch Flankenangriffe abwehren.</p>
      </Description>
      <Ability id="prevent-flanking" />
    </UnitCategory>
    <UnitCategory id="cavalry">
      <Name>cavalry</Name>
      <Name lang="de_DE">Reiter</Name>
      <Description>
        <p>English description here.</p>
      </Description>
      <Description lang="de_DE">
        <p>Berittene Einheiten bewegen sich schnell auf dem Schlachtfeld, und sind als einzige in der Lage, die gegnerischen Fußtruppen zu umgehen und feindliche Fernkämpfer direkt anzugreifen (Flankenangriff).</p>
      </Description>
      <Ability id="flanking" />
    </UnitCategory>
    <UnitCategory id="artillery">
      <Name>artillery</Name>
      <Name lang="de_DE">Fernkämpfer</Name>
      <Description>
        <p>English description here.</p>
      </Description>
      <Description lang="de_DE">
        <p>Die Fernkämpfer schießen aus sicherer Distanz auf den Gegner, vorzugsweise auf Fußsoldaten. Im Nahkampf sind sie extrem anfällig.</p>
      </Description>
    </UnitCategory>
  </UnitCategories>
  <UnitTypes>
    <Unit id="thrower" category="artillery">
      <Name>Stone Hurler</Name>
      <Name lang="de_DE">Kieselsteinwerfer</Name>
      <Description lang="de_DE">
        <p>Große Steine, kleine Steine, ein Kieselsteinwerfer mag sie alle, solange er sie jemandem an den Kopf werfen kann. Ok, zugegeben, die kleinen mag er ein bisschen lieber. Nichtsdestotrotz kann er moderaten kritischen Schaden zufügen - denn, wie jeder weiß, das kann auch ins Auge gehen.</p> 
      </Description>
      <Description lang="en_US">
        <p>Small Stones, big Stones, a Stone Hurler likes them all, as long as he can throw them at people. Ok, granted, the small ones are slightly prefered... Nevertheless, he may inflict moderate critical damage by sometimes hitting an opponent's eye.'</p>
      </Description>
      <Velocity>1</Velocity>
      <ActionPoints>4</ActionPoints>
      <Initiative>1</Initiative>
      <Attack>15</Attack>
      <CriticalDamage chance="0.01">8</CriticalDamage>
      <Armor>2</Armor>
      <Hitpoints>30</Hitpoints>
      <Effectiveness category="infantry">1</Effectiveness>
      <Effectiveness category="cavalry">0.2</Effectiveness>
      <Effectiveness category="artillery">1</Effectiveness>
    </Unit>
    <Unit id="skewer" category="infantry">
      <Name>Skewer</Name>
      <Name lang="de_DE">Bratspießträger</Name>
      <Description lang="de_DE">
        <p>Der Umgang mit der Waffe ist schnell gelernt: Das spitze Ende muss nach vorn!</p> 
      </Description>
      <Description lang="en_US">
        <p>Skewer Crew training 101: stick'em with the pointy end!</p>
      </Description>
      <Velocity>1</Velocity>
      <ActionPoints>4</ActionPoints>
      <Initiative>1</Initiative>
      <Attack>10</Attack>
      <CriticalDamage chance="0.01">2</CriticalDamage>
      <Armor>8</Armor>
      <Hitpoints>90</Hitpoints>
      <Effectiveness category="infantry">0.6</Effectiveness><!-- due to the long weapon reduced effectivity against infantry but full effectivity against cavalry. a standard infantry (short weapon) would have effectivity 1 against infantry and reduced effictivity against cavalry, right?! -->
      <Effectiveness category="cavalry">1</Effectiveness>
      <Effectiveness category="artillery">1</Effectiveness>
    </Unit>
    <Unit id="light_cavalry" category="cavalry">
      <Name>Ostrich Riders</Name>
      <Name lang="de_DE">Straußenreiter</Name>
      <Description lang="de_DE">
        <p>Die Straußenreiter sind äußerst schnell, dafür aber nur schwach gepanzert.</p> 
      </Description>
      <Description lang="en_US">
        <p>Ostrich riders are very quick, but only lightly armored.</p>
      </Description>
      <Velocity>1.5</Velocity>
      <ActionPoints>5</ActionPoints>
      <Initiative>1</Initiative>
      <Attack>10</Attack>
      <CriticalDamage chance="0.002">10</CriticalDamage>
      <Armor>4</Armor>
      <Hitpoints>60</Hitpoints>
      <Effectiveness category="infantry">0.3</Effectiveness>
      <Effectiveness category="cavalry">1</Effectiveness>
      <Effectiveness category="artillery">1</Effectiveness>
    </Unit>
	</UnitTypes>
</Rules>

=== mawiegand/game_server/rules/units/rules_units_skewer.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Rules SYSTEM "../rules.dtd">

    <Unit id="skewer" category="infantry">
      <Name>Skewer</Name>
      <Name lang="de_DE">Bratspießträger</Name>
      <Description lang="de_DE">
        <p>Der Umgang mit der Waffe ist schnell gelernt: Das spitze Ende muss nach vorn!</p> 
      </Description>
      <Description lang="en_US">
        <p>Skewer Crew training 101: stick'em with the pointy end!</p>
      </Description>
      <Cost id="resource_stone" round="true">2</Cost>  
      <Cost id="resource_wood" round="true">10</Cost>    
      <Cost id="resource_fur" round="true">4</Cost>    
      <ProductionTime shortenable="true">300</ProductionTime>   
	  <Requirement id="building_firing_range" min_level="11" />	  
      <Velocity>1</Velocity>
      <ActionPoints>4</ActionPoints>
      <Initiative>15</Initiative>
      <Attack>14</Attack>
      <CriticalDamage chance="0.01" >6</CriticalDamage>
      <Armor>14</Armor>
      <Overrunnable>true</Overrunnable>
      <Hitpoints>90</Hitpoints>
      <Effectiveness category="infantry">0.6</Effectiveness><!-- due to the long weapon reduced effectivity against infantry but full effectivity against cavalry. a standard infantry (short weapon) would have effectivity 1 against infantry and reduced effictivity against cavalry, right?! -->
      <Effectiveness category="cavalry">1</Effectiveness>
      <Effectiveness category="artillery">1</Effectiveness>
      <Effectiveness category="siege">1</Effectiveness>     
    </Unit>

=== mawiegand/game_server/rules/units/rules_units_thrower_3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Rules SYSTEM "../rules.dtd">

    <Unit id="thrower_3" category="unitcategory_artillery">
      <Name>Pebble Thrower3</Name>
      <Name lang="de_DE">Steinschleuderer</Name>
      <Description lang="de_DE">
        <p>Mit der Schleuder können größere Steine weiter geworfen werden. So trifft der Steinschleuderer oft die unvorbereiteten Kämpfer in der zweiten Reihe wodurch insgesamt deutlich mehr Opfer zu beklagen bzw. zu bejubeln sind. Je nach der Seite des Kampfes auf der man gerade steht. Was durchaus nicht immer eindeutig ist.</p> 
      </Description>
      <Description lang="en_US">
        <p>You can throw bigger stones even further if you use a catapult. Stone throwers often hit unsuspecting warriors in the second row, leading to a much higher number of overall casualties that are either suffered or celebrated, depending on which side of the battle you happen to be. Which isn’t always obvious.</p>
      </Description>
      <Flavour lang="en_US">
        <p>Aiming is for sissies. The stone throwers‘ motto is: “The further you can throw the stone, the better!” Sometimes they’re right.</p>
      </Flavour>
      <Flavour lang="de_DE">
        <p>Zielen ist was für Anfänger. Das Motto der Steinschleuderer: 'Je weiterer der Stein geworfen wird, desto besser!' Stimmt sogar manchmal.</p>
      </Flavour>
      <Cost id="resource_stone" round="true">90</Cost>  
      <Cost id="resource_wood" round="true">90</Cost>
      <Cost id="resource_fur" round="true">140</Cost>    
      <ProductionTime shortenable="true">1050</ProductionTime>  
      <Velocity>1</Velocity>
      <ActionPoints>4</ActionPoints>
      <Initiative>8</Initiative>
      <Attack>10</Attack>
      <CriticalDamage chance="0.05">7</CriticalDamage>
      <Armor>3</Armor>
      <Overrunnable>true</Overrunnable>
      <Hitpoints>50</Hitpoints>
      <Effectiveness category="unitcategory_infantry">1.5</Effectiveness>
      <Effectiveness category="unitcategory_cavalry">0.75</Effectiveness>
      <Effectiveness category="unitcategory_artillery">0.75</Effectiveness>
      <Effectiveness category="unitcategory_siege">0.8</Effectiveness>  
      <Effectiveness category="unitcategory_special">1</Effectiveness>   
      <RequirementGroup>
        <Requirement id="building_artillery_tower" min_level="15" />
        <Requirement id="building_fortress_fortification" min_level="14" />
      </RequirementGroup>
      <RequirementGroup>
        <Requirement id="building_firing_range" min_level="15" />
      </RequirementGroup>
    </Unit>

=== mawiegand/game_server/rules/units/rules_units_babysaurus.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Rules SYSTEM "../rules.dtd">

    <Unit id="babysaurus" category="unitcategory_cavalry">
      <Name>Babysaurus</Name>
      <Name lang="de_DE">Babysaurus</Name>
      <Description lang="de_DE">
        <p>Die Babysaurier haben noch keine spitzen Zähne, man kann zwar besser auf ihnen reiten, aber der Reiter muss dafür selbst die Keule schwingen.</p> 
      </Description>
      <Description lang="en_US">
        <p>Babysaurus's teeth are not sharp. They are easy to ride but their rider has to kill his enemies himself.</p>
      </Description>
      <Cost id="resource_stone" round="true">50</Cost>  
      <Cost id="resource_wood" round="true">70</Cost>    
      <Cost id="resource_fur" round="true">35</Cost>    
      <ProductionTime shortenable="true">900</ProductionTime>  
	  <Requirement id="building_stud" min_level="1" />
	  <Velocity>1.5</Velocity>
      <ActionPoints>4</ActionPoints>
      <Initiative>26</Initiative>
      <Attack>17</Attack>
      <CriticalDamage chance="0.01">4</CriticalDamage>
      <Armor>13</Armor>
      <Overrunnable>true</Overrunnable>
      <Hitpoints>80</Hitpoints>
      <Effectiveness category="unitcategory_infantry">0.92</Effectiveness>
      <Effectiveness category="unitcategory_cavalry">1</Effectiveness>
      <Effectiveness category="unitcategory_artillery">1.2</Effectiveness>
      <Effectiveness category="unitcategory_siege">0.8</Effectiveness>   
    </Unit>

=== mawiegand/game_server/rules/units/rules_units_great_chief.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Rules SYSTEM "../rules.dtd">

<Unit id="great_chief" category="unitcategory_special" experienceFactor="0.0" trainable="false">
  <Name>Great Chief</Name>
  <Name lang="de_DE">Großer Häuptling</Name>
  <Description lang="de_DE">
    <p>Der Große Häuptling kann einen Heimatsiedlung gründen und ernennt sich dann selber zum Chef.</p>
  </Description>
  <Description lang="en_US">
    <p>As a scheming, workaholic, slick wannabe, the great chief is a role model for entire generations of snobs. At least, he isn't that tall. Actually, he's rather small. But please, don't let him know.</p>
  </Description>
  <Flavour lang="en_US">
    <p>The great chief is allowed to set up a new home settlement and found a tribe.</p>
  </Flavour>
  <Flavour lang="de_DE">
    <p>Der Große Häuptling kann eine Heimatsiedlung und damit einen neuen Stamm gründen.</p>
  </Flavour>
  <Cost id="resource_stone" round="true">500000</Cost>  
  <Cost id="resource_wood" round="true">500000</Cost>    
  <Cost id="resource_fur" round="true">400000</Cost>    
  <ProductionTime shortenable="true">432000</ProductionTime>
  <Velocity>5.00</Velocity>
  <ActionPoints>4</ActionPoints>
  <Initiative>20</Initiative>
  <Attack>10</Attack>
  <CriticalDamage chance="0.01">50</CriticalDamage>
  <Armor>3</Armor>
  <Overrunnable>true</Overrunnable>
  <Hitpoints>300</Hitpoints>
  <Effectiveness category="unitcategory_infantry">1</Effectiveness>
  <Effectiveness category="unitcategory_cavalry">0.5</Effectiveness>
  <Effectiveness category="unitcategory_artillery">1</Effectiveness>
  <Effectiveness category="unitcategory_siege">1</Effectiveness>
  <Effectiveness category="unitcategory_special">1</Effectiveness>
  <RequirementGroup>
  	<Requirement id="building_stud" min_level="100" />
  </RequirementGroup>
  <!-- add ability to found settlement here not in category -->    
  <CanCreate id="settlement_home_base" />
</Unit>
